[[main]]
  identifier = "about"
  name = "acerca de"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "archivo"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "galeria"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "fiverr"
  url = "gallery/mine"

[[main]]
  identifier = "posts"
  name = "entradas"
  url = "posts"
  weight = 4